{
    "name": "Sale Order Lot Selection FEFO",
    "version": "19.0.3.0.0",
    "category": "Sales Management",
    "author": "Daniel Domínguez (xtendoo)",
    "website": "https://xtendoo.es",
    "license": "AGPL-3",
    "depends": ["sale_stock", "purchase_stock", "product_expiry", "account"],
    "data": [
        "security/ir.model.access.csv",
        "views/account_move_views.xml",
        "views/purchase_order_views.xml",
        "views/sale_order_views.xml",
        "views/stock_picking_views.xml",
        "reports/sale_order_report_templates.xml",
        "reports/account_invoice_report_templates.xml",
        "reports/stock_picking_report_templates.xml",
        "reports/sale_report_views.xml",
    ],
    "demo": ["demo/sale_demo.xml"],
    "maintainers": ["bodedra"],
    "installable": True,
}
